"""Add OTP fields to User model

Revision ID: f1ab2590c46a
Revises: 
Create Date: 2025-09-28 21:32:07.042600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ab2590c46a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('budget')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('otp_verified_at')
        batch_op.drop_column('otp_verified')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
